name: rag-chatbot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain
      - langchain-openai
      - langchain-community
      - langchain-huggingface
      - langchain-text-splitters
      - sentence-transformers
      - faiss-cpu
      - streamlit
      - python-dotenv
      - pypdf
