name: rag-chatbot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain
      - langchain-openai
      - langchain-community
      - streamlit
      - python-dotenv
      - pypdf
